import OpenAI from 'openai';

// We use the OpenAI SDK because both Groq and Cerebras offer OpenAI-compatible endpoints.
export const groqClient = new OpenAI({
  apiKey: process.env.GLOBAL_GROQ_API_KEY,
  baseURL: 'https://api.groq.com/openai/v1',
});

export const cerebrasClient = new OpenAI({
  apiKey: process.env.GLOBAL_CEREBRAS_API_KEY,
  baseURL: 'https://api.cerebras.ai/v1',
});

// Helper for magic prompts
export async function generateMagicPrompt(description: string): Promise<string> {
  const response = await groqClient.chat.completions.create({
    model: 'llama3-70b-8192',
    messages: [
      {
        role: 'system',
        content: `You are an expert AI Voice Agent Prompt Engineer. 
Your job is to take a short description of an agent from a user and expand it into a highly structured, comprehensive system prompt for a voice AI agent.

The prompt you output must include:
1. **Identity & Persona**: Who the agent is, its tone, and style.
2. **Primary Objective**: The main goal of the conversation.
3. **Core Constraints**: What the agent MUST NOT do (e.g., don't hallucinate pricing, keep responses under 2 sentences, etc.).
4. **Conversation Flow / Strategy**: How to guide the caller step by step.
5. **Edge Cases**: How to handle off-topic questions, anger, or confusion.

Keep the output professional and directly ready to be used as a system prompt. Do not include introductory text like "Here is your prompt", just output the prompt itself.`
      },
      {
        role: 'user',
        content: `Short description: ${description}`
      }
    ],
    temperature: 0.7,
    max_tokens: 1500,
  });

  return response.choices[0]?.message?.content?.trim() || '';
}

// Helper for schema generation
export async function generateSchema(description: string): Promise<any> {
  const response = await cerebrasClient.chat.completions.create({
    model: 'llama3.1-8b', // You can use whichever cerebras model is preferred, assuming standard names
    messages: [
      {
        role: 'system',
        content: `You are an expert at generating strict JSON schemas for data extraction.
The user will describe the data they want to extract from a conversation.
You must output a valid JSON Schema object (Draft 7).
Do NOT wrap the output in markdown code blocks like \`\`\`json. Just output the raw JSON object.
Do NOT include any explanatory text.`
      },
      {
        role: 'user',
        content: `Description: ${description}`
      }
    ],
    temperature: 0.1,
    max_tokens: 1000,
  });

  const raw = response.choices[0]?.message?.content?.trim() || '{}';
  try {
    return JSON.parse(raw);
  } catch (e) {
    console.error("Failed to parse schema generated by Cerebras:", raw);
    return {};
  }
}
